In [8]:
import numpy as np

A = [[1, 2, 3],
     [4, 5, 6]]
B = [[1, 2],
     [3, 4],
     [5, 6]]

def shape(A):
    num_rows = len(A)
    num_cols = len(A[0]) if A else 0
    return num_rows, num_cols

def get_row(A, i):
    return A[i]

def get_column(A, j):
    return [A[j] for A_i in A]

### creating a matrix using nested list comprehension 
def make_matrix(num_rows, num_cols, etry_fn):
    return [[is_diagonal(i, j) for j in range(num_cols)] for i in range(num_rows)]

def is_diagonal(i, j):
    return 1 if i==j else 0

identity_matrix = make_matrix(5, 5, is_diagonal)
print(identity_matrix)


[[1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 1]]


In [9]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [13]:
### add matrix
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
print(B)
C = A+B
print("Matrix A + B:\n",C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
Matrix A + B:
 [[ 2  4  6]
 [ 8 10 12]]


In [14]:
### matrix substruct
C = A-B
print(A)
print(B)
print("Matrix A - B:\n",C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
Matrix A - B:
 [[0 0 0]
 [0 0 0]]


In [15]:
### Matrix multiplication
print(A)
print(B)
C = A*B
print("Matrix A * B:\n",C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
Matrix A * B:
 [[ 1  4  9]
 [16 25 36]]


In [16]:
### Matrix division
C = A/B
print(A)
print(B)
print("Matrix A/B: \n", C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
Matrix A/B: 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
### Transpose matrix
A = np.array([[1, 2],[3, 4], [5, 6]])
print(A)
C = A.T
print("Transpose of Matrix: \n", C)

[[1 2]
 [3 4]
 [5 6]]
Transpose of Matrix: 
 [[1 3 5]
 [2 4 6]]


In [23]:
### First, we define a small 2×2 matrix, then calculate the inverse of the matrix, and then confirm the inverse by multiplying it with the original matrix to give the identity matrix.
from numpy.linalg import inv

# define matrix
A = np.array([[1.0, 2.0], [3.0, 4.0]])
print(A)
# invert matrix
B = inv(A)
print(B)
# multiply A and B
I = A.dot(B)
print(I)

[[1. 2.]
 [3. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [25]:
### A trace of a square matrix is the sum of the values on the main diagonal of the matrix (top-left to bottom-right)

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)
B = np.trace(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


In [26]:
### The determinant of a square matrix is a scalar representation of the volume of the matrix.

from numpy.linalg import det
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)
B = det(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-9.51619735392994e-16


In [28]:
### The rank of a matrix is the estimate of the number of linearly independent rows or columns in a matrix.
from numpy.linalg import matrix_rank
# rank
v1 = np.array([1,2,3])
print(v1)
vr1 = matrix_rank(v1)
print(vr1)
# zero rank
v2 = np.array([0,0,0,0,0])
print(v2)
vr2 = matrix_rank(v2)
print(vr2)

[1 2 3]
1
[0 0 0 0 0]
0
